# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  postgres-db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    # volume и связанная с ним директория в контейнере
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data/

  bot:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      -  .env


volumes:
  postgres-db: